version: '3.8'
services:
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    networks:
      - npm
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /data/volumes/npm:/data
      - /data/volumes/letsencrypt:/etc/letsencrypt
networks:
  npm:
